apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastify-auth-ingress
  labels:
    app: fastify-auth-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: fastify-auth.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastify-auth-service
            port:
              number: 8000

